export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const TOGGLE_ONE_TASK = 'TOGGLE_ONE_TASK';
export const TOGGLE_ADD_TASK_MODAL = 'TOGGLE_ADD_TASK_MODAL';
export const FETCH_DATA_FIRST_TIME = 'FETCH_DATA_FIRST_TIME';
export const REFRESH_STATE = 'REFRESH_STATE';
